# Generated by Django 5.1.3 on 2024-11-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_author_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
