# Generated by Django 5.1.3 on 2024-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_remove_recipe_author_remove_category_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_cooking',
            field=models.CharField(max_length=200),
        ),
    ]
