# Generated by Django 5.1.3 on 2024-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_alter_recipe_ingredients_alter_recipe_steps_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_dish',
            field=models.ImageField(upload_to='media/recipes/'),
        ),
    ]
