# Generated by Django 5.1.3 on 2024-11-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_recipe_image_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
